#
# Copyright (c) 2006-2013 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - http://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    module:
        zenoss_daemon_csrf:
            enable: true
            category: "Exploits"
            name: "Zenoss 3.x Daemon CSRF"
            description: "Attempts to start/stop/restart daemons on a Zenoss Core 3.x server."
            authors: ["bcoles"]
            target:
                working: ["ALL"]
