#
# Copyright (c) 2006-2013 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - http://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    module:
         get_visited_domains:
            enable: true
            category: "Browser"
            name: "Get Visited Domains"
            description: "This module will retrieve rapid history extraction through non-destructive cache timing.\nBased on work done at http://lcamtuf.coredump.cx/cachetime/"
            authors: ["keith_lee @keith55 http://milo2012.wordpress.com"]
            target:
                working: ["FF", "IE"]
                not_working: ["O", "C", "S"]
